version: 0.2

phases:
  install:
    commands:
      - echo installing dependencies
      - npm install
  pre_build:
    commands:
      - echo running pre_build
      - npm run test
  build:
    commands:
      - echo runnign build command
      - npm run build
      - echo runnign tests
      - npm test
  post_build:
    commands:
      - echo build completed on `date`
artifacts:
  files:
    - build/*
  discard-paths: yes
